Repository Mi-Ss-A/usersvc, pull requests merged in 2024-11, with the labels that each got.

#4 feat:SpringBoot 초기 설정(#2)
  missa/.gitattributes
  missa/.gitignore
  missa/build.gradle
  missa/gradle/wrapper/gradle-wrapper.jar
  missa/gradle/wrapper/gradle-wrapper.properties
  missa/gradlew
  missa/gradlew.bat
  missa/settings.gradle
  missa/src/main/java/com/wibeechat/missa/MissaApplication.java
  missa/src/main/resources/application.properties
  missa/src/test/java/com/wibeechat/missa/MissaApplicationTests.java
Labels: feat

#5 Delete missa directory
  missa/.gitattributes
  missa/.gitignore
  missa/build.gradle
  missa/gradle/wrapper/gradle-wrapper.jar
  missa/gradle/wrapper/gradle-wrapper.properties
  missa/gradlew
  missa/gradlew.bat
  missa/settings.gradle
  missa/src/main/java/com/wibeechat/missa/MissaApplication.java
  missa/src/main/resources/application.properties
  missa/src/test/java/com/wibeechat/missa/MissaApplicationTests.java
Labels: refactor

#6 feat:SpringBoot 초기세팅(#2)
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/wibeechat/missa/MissaApplication.java
  src/main/resources/application.properties
  src/test/java/com/wibeechat/missa/MissaApplicationTests.java
Labels: feat, refactor

#7 feat:폴더구조 생성(#3)
  src/main/java/com/wibeechat/missa/config/test.txt
  src/main/java/com/wibeechat/missa/controller/test.txt
  src/main/java/com/wibeechat/missa/dto/test.txt
  src/main/java/com/wibeechat/missa/entity/test.txt
  src/main/java/com/wibeechat/missa/repository/test.txt
  src/main/java/com/wibeechat/missa/service/test.txt
Labels: feat, refactor

#20 feat : login api 및 에러처리 (#9)
  build.gradle
  src/main/java/com/wibeechat/missa/controller/user/LoginController.java
  src/main/java/com/wibeechat/missa/dto/login/LoginRequest.java
  src/main/java/com/wibeechat/missa/dto/login/LoginResponse.java
  src/main/java/com/wibeechat/missa/entity/BankAccountInfo.java
  src/main/java/com/wibeechat/missa/entity/Gender.java
  src/main/java/com/wibeechat/missa/entity/UserInfo.java
  src/main/java/com/wibeechat/missa/entity/UserStatus.java
  src/main/java/com/wibeechat/missa/exception/BaseException.java
  src/main/java/com/wibeechat/missa/exception/ErrorCode.java
  src/main/java/com/wibeechat/missa/exception/ErrorResponse.java
  src/main/java/com/wibeechat/missa/exception/InvalidPasswordException.java
  src/main/java/com/wibeechat/missa/exception/UserNotFoundException.java
  src/main/java/com/wibeechat/missa/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/wibeechat/missa/repository/UserInfoRepository.java
  src/main/java/com/wibeechat/missa/service/user/UserService.java
  src/main/resources/application.properties
  src/test/java/com/wibeechat/missa/LoginControllerIntegrationTest.java
  src/test/java/com/wibeechat/missa/LoginControllerTest.java
  src/test/java/com/wibeechat/missa/MissaApplicationTests.java
Labels: feat

#21 feat: 세션 처리 및 에러처리
  build.gradle
  src/main/java/com/wibeechat/missa/annotation/CurrentUser.java
  src/main/java/com/wibeechat/missa/annotation/LoginRequired.java
  src/main/java/com/wibeechat/missa/component/CurrentUserArgumentResolver.java
  src/main/java/com/wibeechat/missa/component/SessionManager.java
  src/main/java/com/wibeechat/missa/config/SwaggerConfig.java
  src/main/java/com/wibeechat/missa/config/WebMvcConfig.java
  src/main/java/com/wibeechat/missa/controller/user/LoginController.java
  src/main/java/com/wibeechat/missa/entity/UserInfo.java
  src/main/java/com/wibeechat/missa/interceptor/LoginCheckInterceptor.java
  src/main/java/com/wibeechat/missa/service/user/UserService.java
  src/main/resources/application.properties
  src/test/java/com/wibeechat/missa/LoginControllerTest.java
Labels: feat

#22 refactor: mysql to oracle db
  .gitignore
  build.gradle
  src/main/java/com/wibeechat/missa/entity/UserInfo.java
  src/main/java/com/wibeechat/missa/entity/UserStatus.java
  src/main/java/com/wibeechat/missa/entity/test.txt
  src/main/java/com/wibeechat/missa/repository/test.txt
  src/main/java/com/wibeechat/missa/service/test.txt
  src/main/resources/application.properties
  src/test/java/com/wibeechat/missa/LoginControllerIntegrationTest.java
Labels: feat, refactor

#23 feat: postgre databse 멀티 db 설정
  build.gradle
  src/main/java/com/wibeechat/missa/MissaApplication.java
  src/main/java/com/wibeechat/missa/config/MysqlConfig.java
  src/main/java/com/wibeechat/missa/config/PostgresConfig.java
  src/main/java/com/wibeechat/missa/config/SwaggerConfig.java
  src/main/java/com/wibeechat/missa/controller/history/HistoryController.java
  src/main/java/com/wibeechat/missa/controller/user/LoginController.java
  src/main/java/com/wibeechat/missa/dto/history/ChatSaveRequest.java
  src/main/java/com/wibeechat/missa/dto/history/ChatSaveResponse.java
  src/main/java/com/wibeechat/missa/entity/mysql/BankAccountInfo.java
  src/main/java/com/wibeechat/missa/entity/mysql/Gender.java
  src/main/java/com/wibeechat/missa/entity/mysql/UserInfo.java
  src/main/java/com/wibeechat/missa/entity/mysql/UserStatus.java
  src/main/java/com/wibeechat/missa/entity/postgresql/ChatMessage.java
  src/main/java/com/wibeechat/missa/repository/UserInfoRepository.java
  src/main/java/com/wibeechat/missa/repository/mysql/UserInfoRepository.java
  src/main/java/com/wibeechat/missa/repository/postgres/ChatMessageRepository.java
  src/main/java/com/wibeechat/missa/service/history/ChatService.java
  src/main/java/com/wibeechat/missa/service/user/UserService.java
  src/main/resources/application.properties
  src/test/java/com/wibeechat/missa/userhistory/UserHistoryControllerTest.java
  src/test/java/com/wibeechat/missa/userhistory/UserHistoryRepositoryTest.java
  src/test/java/com/wibeechat/missa/userlogin/LoginControllerIntegrationTest.java
  src/test/java/com/wibeechat/missa/userlogin/LoginControllerTest.java
Labels: feat

#27 feat: redis 설정 및 user 로그인 정보 변경
  build.gradle
  src/main/java/com/wibeechat/missa/component/SessionManager.java
  src/main/java/com/wibeechat/missa/config/RedisSessionListener.java
  src/main/java/com/wibeechat/missa/config/SessionConfig.java
  src/main/java/com/wibeechat/missa/config/WebMvcConfig.java
  src/main/java/com/wibeechat/missa/controller/history/HistoryController.java
  src/main/java/com/wibeechat/missa/controller/user/LoginController.java
  src/main/java/com/wibeechat/missa/service/history/ChatService.java
  src/main/resources/application.properties
Labels: feat, refactor

#33 feat:prod 설정을 위한 DB connection 변경(#32)
  build.gradle
  src/main/java/com/wibeechat/missa/config/MysqlConfig.java
  src/main/java/com/wibeechat/missa/config/PostgresConfig.java
  src/main/resources/application.properties
  src/test/java/com/wibeechat/missa/userhistory/UserHistoryControllerTest.java
Labels: refactor

#35 refactor:test 폴더 삭제(#34)
  src/test/java/com/wibeechat/missa/userhistory/UserHistoryControllerTest.java
  src/test/java/com/wibeechat/missa/userhistory/UserHistoryRepositoryTest.java
  src/test/java/com/wibeechat/missa/userlogin/LoginControllerIntegrationTest.java
  src/test/java/com/wibeechat/missa/userlogin/LoginControllerTest.java
Labels: refactor

#37 refactor: 로그아웃 기능 수정
  src/main/java/com/wibeechat/missa/controller/user/LoginController.java
Labels: refactor

#40 refactor: loginRequired 어노테이션 추가
  src/main/java/com/wibeechat/missa/controller/user/LoginController.java
Labels: refactor

#43 bug: 로그인 문제 버그 잡기 (#42)
  src/main/java/com/wibeechat/missa/config/RedisSessionListener.java
  src/main/java/com/wibeechat/missa/config/SessionConfig.java
  src/main/java/com/wibeechat/missa/controller/user/LoginController.java
  src/main/java/com/wibeechat/missa/dto/login/LoginRequest.java
  src/main/java/com/wibeechat/missa/dto/login/LoginResponse.java
  src/main/java/com/wibeechat/missa/entity/postgresql/ChatMessage.java
  src/main/java/com/wibeechat/missa/interceptor/LoginCheckInterceptor.java
  src/main/java/com/wibeechat/missa/service/user/UserService.java
  src/main/resources/application.properties
Labels: bug, refactor

#44 Refactor deploy
  src/main/java/com/wibeechat/missa/config/RedisSessionListener.java
  src/main/java/com/wibeechat/missa/config/SessionConfig.java
  src/main/java/com/wibeechat/missa/controller/user/LoginController.java
  src/main/java/com/wibeechat/missa/dto/login/LoginRequest.java
  src/main/java/com/wibeechat/missa/dto/login/LoginResponse.java
  src/main/java/com/wibeechat/missa/entity/postgresql/ChatMessage.java
  src/main/java/com/wibeechat/missa/interceptor/LoginCheckInterceptor.java
  src/main/java/com/wibeechat/missa/service/user/UserService.java
  src/main/resources/application.properties
Labels: bug, feat, help, refactor

#46 feat: get redis session id (#45)
  src/main/java/com/wibeechat/missa/config/RedisSessionListener.java
  src/main/java/com/wibeechat/missa/controller/user/LoginController.java
Labels: feat
